# Generated by Django 6.0.4 on 2026-04-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_brand_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='url',
        ),
    ]
